language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "daniftinca-github"
notifications:
  email: false
  on_success: never
  on_failure: always
script:
  - sonar-scanner
jdk:
  - oraclejdk8
script:
  # the following command line builds the project, runs the tests with coverage and then  execute the SonarQube analysis
  # sonar token : 512d729f7b1fb80369c09b2147acdb65808dd691
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=daniftinca_mitblick -Dsonar.organization=daniftinca-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=512d729f7b1fb80369c09b2147acdb65808dd691




  # mvn sonar:sonar -Dsonar.projectKey=daniftinca_mitblick -Dsonar.organization=daniftinca-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=512d729f7b1fb80369c09b2147acdb65808dd691